# Generated by Django 3.2.7 on 2021-10-05 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211005_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 14, 6, 46, 142509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 14, 6, 46, 141326, tzinfo=utc)),
        ),
    ]
