# Generated by Django 3.2.4 on 2021-10-15 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211015_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 9, 4, 34, 825241, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 9, 4, 34, 824512, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(),
        ),
    ]
