# Generated by Django 3.2.4 on 2021-10-15 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20211015_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 9, 14, 10, 613085, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 9, 14, 10, 612274, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='django-db-models-fields-charfield', unique=True),
        ),
    ]
