# Generated by Django 3.2.4 on 2021-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='img/avatar.png', null=True, upload_to='avatar', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=255, unique=True, verbose_name='Adresse Email'), max_length=200, unique=True),
        ),
    ]
