# Generated by Django 3.2.4 on 2021-10-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211007_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=255, unique=True, verbose_name='Adresse Email'), max_length=200),
        ),
    ]
