# Generated by Django 3.2.4 on 2021-10-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('N', 'Newbie'), ('P', 'Pro')], default='Newbie', max_length=200),
        ),
    ]
