# Generated by Django 3.2.4 on 2021-10-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/staticfiles/img/avatar.png', null=True, upload_to='avatar', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
