# Generated by Django 3.2.4 on 2021-10-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_username',
        ),
    ]
