# Generated by Django 3.2.4 on 2021-10-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_user_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_username',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
